# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-03 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_id', models.CharField(max_length=5, verbose_name='\u7c7b\u522b\u7f16\u53f7')),
                ('cate_name', models.CharField(max_length=30, verbose_name='\u7c7b\u522b\u540d\u79f0')),
                ('remark', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5907\u6ce8')),
                ('complete_status', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5b8c\u6210\u60c5\u51b5')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u7c7b\u522b',
                'verbose_name_plural': '\u8bbe\u5907\u7c7b\u522b',
            },
        ),
        migrations.AlterField(
            model_name='devicemessage',
            name='category_name',
            field=models.CharField(choices=[('lift_dev', '\u8d77\u91cd\u673a\u68b0'), ('car', '\u6c7d\u8f66')], max_length=30, verbose_name='\u7c7b\u522b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='devicemessage',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image/%Y/%m', verbose_name='\u8bbe\u5907\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='devicemessage',
            name='make_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5236\u9020\u5355\u4f4d'),
        ),
    ]
