# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-05 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20180403_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceOutsource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_id', models.CharField(max_length=20, verbose_name='\u53d8\u66f4\u7f16\u53f7')),
                ('parts_name', models.CharField(max_length=30, verbose_name='\u914d\u4ef6\u540d\u79f0')),
                ('spec_model', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u89c4\u683c\u578b\u53f7')),
                ('num', models.CharField(max_length=5, verbose_name='\u6570\u91cf')),
                ('tax_price', models.CharField(max_length=10, verbose_name='\u542b\u7a0e\u4ef7\u683c')),
                ('tax_rate', models.CharField(max_length=10, verbose_name='\u7a0e\u7387')),
                ('no_tax_price', models.CharField(max_length=10, verbose_name='\u4e0d\u542b\u7a0e\u4ef7\u683c')),
                ('remark', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u59d4\u5916\u8bb0\u5f55',
                'verbose_name_plural': '\u8bbe\u5907\u59d4\u5916\u8bb0\u5f55',
            },
        ),
        migrations.AlterField(
            model_name='devicemessage',
            name='belong_id',
            field=models.CharField(choices=[('G0', 'G0'), ('G8', 'G8'), ('G6', 'G6')], max_length=5, verbose_name='\u6240\u5c5e\u90e8\u95e8\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='devicemessage',
            name='device_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8bbe\u5907\u578b\u53f7'),
        ),
    ]
