# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-10 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20180405_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20, verbose_name='\u8bbe\u5907\u7f16\u53f7')),
                ('device_name', models.CharField(max_length=10, verbose_name='\u8bbe\u5907\u540d\u79f0')),
                ('reason', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u7533\u8bf7\u539f\u56e0')),
                ('device_status', models.CharField(choices=[('repair', '\u7ef4\u4fee'), ('normal', '\u6b63\u5e38'), ('check', '\u68c0\u67e5')], default='repair', max_length=10, verbose_name='\u8bbe\u5907\u72b6\u6001')),
                ('apply_unit', models.CharField(choices=[('G0', 'G0'), ('G8', 'G8'), ('G6', 'G6')], max_length=5, verbose_name='\u7533\u8bf7\u90e8\u95e8')),
                ('apply_id', models.CharField(max_length=20, verbose_name='\u7533\u8bf7\u7f16\u53f7')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u7ef4\u4fee\u8bb0\u5f55',
                'verbose_name_plural': '\u8bbe\u5907\u7ef4\u4fee\u8bb0\u5f55',
            },
        ),
    ]
