# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-21 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_devicerepair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicemessage',
            options={'ordering': ['enter_time'], 'verbose_name': '\u8bbe\u5907\u4fe1\u606f', 'verbose_name_plural': '\u8bbe\u5907\u4fe1\u606f'},
        ),
        migrations.AlterField(
            model_name='devicemessage',
            name='device_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8bbe\u5907\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='devicemessage',
            name='enter',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5f55\u5165\u4eba'),
        ),
        migrations.AlterField(
            model_name='devicemessage',
            name='enter_time',
            field=models.DateField(blank=True, null=True, verbose_name='\u5f55\u5165\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='devicemessage',
            name='manage_unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7ba1\u7406\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='devicemessage',
            name='resp_per',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u8bbe\u5907\u8d1f\u8d23\u4eba'),
        ),
        migrations.AlterField(
            model_name='devicerepair',
            name='apply_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7533\u8bf7\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='devicerepair',
            name='apply_unit',
            field=models.CharField(blank=True, choices=[('G0', 'G0'), ('G8', 'G8'), ('G6', 'G6')], max_length=5, null=True, verbose_name='\u7533\u8bf7\u90e8\u95e8'),
        ),
    ]
