# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-22 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20180422_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBuyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=20, verbose_name='\u8ba1\u5212\u7f16\u53f7')),
                ('parts_name', models.CharField(max_length=30, verbose_name='\u90e8\u4ef6\u540d\u79f0')),
                ('spec_model', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u89c4\u683c\u578b\u53f7')),
                ('num', models.CharField(max_length=5, verbose_name='\u6570\u91cf')),
                ('tax_price', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u542b\u7a0e\u4ef7\u683c')),
                ('tax_rate', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u7a0e\u7387')),
                ('no_tax_price', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u4e0d\u542b\u7a0e\u4ef7\u683c')),
                ('remark', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u8d2d\u7f6e\u8ba1\u5212',
                'verbose_name_plural': '\u8bbe\u5907\u8d2d\u7f6e\u8ba1\u5212',
            },
        ),
        migrations.AlterField(
            model_name='deviceoutsource',
            name='no_tax_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u4e0d\u542b\u7a0e\u4ef7\u683c'),
        ),
        migrations.AlterField(
            model_name='deviceoutsource',
            name='tax_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u542b\u7a0e\u4ef7\u683c'),
        ),
        migrations.AlterField(
            model_name='deviceoutsource',
            name='tax_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u7a0e\u7387'),
        ),
    ]
