# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-22 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20180422_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicebuyplan',
            name='apply_unit',
            field=models.CharField(blank=True, choices=[('G0', 'G0'), ('G8', 'G8'), ('G6', 'G6')], max_length=10, null=True, verbose_name='\u7533\u8bf7\u90e8\u95e8'),
        ),
        migrations.AddField(
            model_name='devicebuyplan',
            name='plan_time',
            field=models.DateField(auto_now=True, null=True, verbose_name='\u8ba1\u5212\u65f6\u95f4'),
        ),
    ]
