# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-23 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20180422_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicebuyplan',
            options={'ordering': ['plan_time'], 'verbose_name': '\u8bbe\u5907\u8d2d\u7f6e\u8ba1\u5212', 'verbose_name_plural': '\u8bbe\u5907\u8d2d\u7f6e\u8ba1\u5212'},
        ),
        migrations.AlterModelOptions(
            name='devicerepair',
            options={'ordering': ['apply_time'], 'verbose_name': '\u8bbe\u5907\u7ef4\u4fee\u8bb0\u5f55', 'verbose_name_plural': '\u8bbe\u5907\u7ef4\u4fee\u8bb0\u5f55'},
        ),
        migrations.AddField(
            model_name='devicebuyplan',
            name='plan_class',
            field=models.CharField(blank=True, choices=[('buy', '\u8d2d\u7f6e'), ('update', '\u66f4\u65b0'), ('recycle', '\u56de\u6536')], max_length=20, null=True, verbose_name='\u8ba1\u5212\u7c7b\u522b'),
        ),
    ]
