# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-23 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20180423_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicebuyplan',
            options={'ordering': ['plan_time'], 'verbose_name': '\u8ba1\u5212', 'verbose_name_plural': '\u8ba1\u5212'},
        ),
        migrations.AddField(
            model_name='devicerepair',
            name='rep_status',
            field=models.CharField(choices=[('wait', '\u5f85\u7ef4\u62a4'), ('ok', '\u5df2\u4fee\u590d')], default='wait', max_length=20, verbose_name='\u8bbe\u5907\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='devicerepair',
            name='apply_id',
            field=models.CharField(default=0, max_length=20, verbose_name='\u7533\u8bf7\u7f16\u53f7'),
        ),
    ]
