# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-02 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_auto_20180423_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicebuyplan',
            name='plan_model',
            field=models.CharField(blank=True, choices=[('ok', '\u5df2\u5ba1\u6279'), ('wait', '\u5f85\u5ba1\u6279')], default='wait', max_length=20, null=True, verbose_name='\u8ba1\u5212\u72b6\u6001'),
        ),
    ]
