# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBuyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=20, verbose_name='\u8ba1\u5212\u7f16\u53f7')),
                ('parts_name', models.CharField(max_length=30, verbose_name='\u90e8\u4ef6\u540d\u79f0')),
                ('spec_model', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u89c4\u683c\u578b\u53f7')),
                ('num', models.CharField(max_length=5, verbose_name='\u6570\u91cf')),
                ('tax_price', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u542b\u7a0e\u4ef7\u683c')),
                ('tax_rate', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u7a0e\u7387')),
                ('no_tax_price', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u4e0d\u542b\u7a0e\u4ef7\u683c')),
                ('remark', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5907\u6ce8')),
                ('plan_time', models.DateField(auto_now=True, null=True, verbose_name='\u8ba1\u5212\u65f6\u95f4')),
                ('apply_unit', models.CharField(blank=True, choices=[('G0', 'G0'), ('G8', 'G8'), ('G6', 'G6')], max_length=10, null=True, verbose_name='\u7533\u8bf7\u90e8\u95e8')),
                ('plan_class', models.CharField(blank=True, choices=[('buy', '\u8d2d\u7f6e'), ('update', '\u66f4\u65b0'), ('recycle', '\u56de\u6536')], max_length=20, null=True, verbose_name='\u8ba1\u5212\u7c7b\u522b')),
                ('plan_model', models.CharField(blank=True, choices=[('ok', '\u5ba1\u6279\u901a\u8fc7'), ('no', '\u5ba1\u6279\u672a\u901a\u8fc7'), ('wait', '\u5f85\u5ba1\u6279')], default='wait', max_length=20, null=True, verbose_name='\u8ba1\u5212\u72b6\u6001')),
                ('plan_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u672a\u901a\u8fc7\u539f\u56e0')),
            ],
            options={
                'ordering': ['plan_time'],
                'verbose_name': '\u8ba1\u5212',
                'verbose_name_plural': '\u8ba1\u5212',
            },
        ),
    ]
