# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-05 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='flag',
            field=models.CharField(choices=[('0', '\u7ba1\u7406\u5458'), ('1', '\u5458\u5de5')], default='1', max_length=2),
        ),
    ]
